language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script: composer install

script: vendor/bin/phpunit